### ISSUE TITLE
测试最佳编码和码率，分辨率等参数

### ISSUE THREAD

**Issue by starcwl** [zijingcloud/iOS-SDK#11]
* 机型：
* iOS系统版本：
* SDK版本:
* 合作伙伴：（如有请填写，没有留空）
* 项目名称：

- [] 这是一个 **Bug**
- [x] 这是一个 **开发建议**
- [] 这是一个 **文档使用问题**

**Comment by zjlizhipeng** [comment]
确定使用三个档位的最佳分辨率 高清、标清、流畅。    数据持续测试，维护。
