### ISSUE TITLE
无法获取丢包情况的问题

### ISSUE THREAD

**Issue by zjlizhipeng** [zijingcloud/iOS-SDK#3]
* 机型：
* iOS系统版本：
* SDK版本:
* 合作伙伴：（如有请填写，没有留空）
* 项目名称：

- [x] 这是一个 **Bug**
- [] 这是一个 **开发建议**
- [] 这是一个 **文档使用问题**

**Comment by starcwl** [comment]
已经改好，请合并zjrtc.js.  @zjlizhipeng
