### ISSUE TITLE
网络切换时退会

### ISSUE THREAD

**Issue by starcwl** [zijingcloud/iOS-SDK#4]
* 机型：
* iOS系统版本：
* SDK版本:
* 合作伙伴：（如有请填写，没有留空）
* 项目名称：

- [] 这是一个 **Bug**
- [x] 这是一个 **开发建议**
- [] 这是一个 **文档使用问题** 

### 代码期望的行为
应该重入，而不是退会

**Comment by zjlizhipeng** [comment]
现在效果是：
在切换网络的时候会提示，"网络切换为wifi\cell，重新连接中...”。
重新连接加入会议。
