### ISSUE TITLE
需求：屏幕分享

### ISSUE THREAD

**Issue by starcwl** [zijingcloud/iOS-SDK#5]
* 机型：
* iOS系统版本：
* SDK版本:
* 合作伙伴：（如有请填写，没有留空）
* 项目名称：

- [] 这是一个 **Bug**
- [x] 这是一个 **开发建议**
- [] 这是一个 **文档使用问题** 

### 代码期望的行为
分享屏幕操作给其他用户

**Comment by zjlizhipeng** [comment]
尚存在问题：
1.视频右上角存在1像素竖线。
2.不能随着设备转动自动适配图片方向。

**Comment by zjlizhipeng** [comment]
解决问题1.

**Comment by zjlizhipeng** [comment]
解决问题2.
