### ISSUE TITLE
请给IOS WebRTC库打补丁，补丁已通过邮件发送 

### ISSUE THREAD

**Issue by jiangjianping** [zijingcloud/iOS-SDK#6]
如题

**Comment by starcwl** [comment]
以下补丁已打
* Cast sequence number in RtpFrameObject.
* Workaround for PacketBuffer bug.
* Check H264 NALUs for frametype and insert SPS/PPS packets into the PacketBuffer.
* Break backwards traversal loop if we have looped around all packets in the PacketBuffer for H264 frames.
* Only create H264 frames if there are no gaps in the packet sequence number.

以下补丁patch 失败：
* Dont request keyframes if the stream is inactive or if we are currently receiving a keyframe.

**Comment by starcwl** [comment]
Only create H264 frames if there are no gaps in the packet sequence number.  已打。
