### ISSUE TITLE
异常退会时，没有及时调用退会请求。

### ISSUE THREAD

**Issue by zijingcloud** [zijingcloud/iOS-SDK#7]
* 机型：
* iOS系统版本：
* SDK版本:
* 合作伙伴：（如有请填写，没有留空）
* 项目名称：

- [] 这是一个 **Bug**
- [x] 这是一个 **开发建议**
- [] 这是一个 **文档使用问题** 

### 代码期望的行为
当应用意外终止时，应该在应用被杀死时调用退会(disconnect)请求。

**Comment by zjlizhipeng** [comment]
原本功能：
1.会中状态出现异常提示时(未知异常、token无效等)，强制退出会议。

最新添加功能：
1.App结束时未退出会议，强制退出会议。
2.App遇到提示程序崩溃时，强制退出会议。
