### ISSUE TITLE
[App]增加应用强制升级

### ISSUE THREAD

**Issue by starcwl** [zijingcloud/iOS-SDK#8]
* 机型：
* iOS系统版本：
* SDK版本:
* 合作伙伴：（如有请填写，没有留空）
* 项目名称：

- [] 这是一个 **Bug**
- [x] 这是一个 **开发建议**
- [] 这是一个 **文档使用问题**

**Comment by zjlizhipeng** [comment]
和后台讨论完成方案。等待后台出Api。

**Comment by zjlizhipeng** [comment]
已经上线并给OEM出使用说明文档。
