### ISSUE TITLE
[App]增加内测功能

### ISSUE THREAD

**Issue by starcwl** [zijingcloud/iOS-SDK#9]
* 机型：
* iOS系统版本：
* SDK版本:
* 合作伙伴：（如有请填写，没有留空）
* 项目名称：

- [] 这是一个 **Bug**
- [] 这是一个 **开发建议**
- [] 这是一个 **文档使用问题**

**Comment by zjlizhipeng** [comment]
在app中  我的 -- 关于 中添加 “测试版本”，“多流” 两个模块。 内侧版本时，打开两个模块，直接点击切换状态。“测试版本”打开时，使用测试地址。 发布正式版本时，关闭两个模块。

**Comment by zjlizhipeng** [comment]
应要求，修改为 添加 开发者模式 版本。  特殊操作： 我的 -- 关于 --  版本号 点击七下出现开发者模式。

**Comment by zjlizhipeng** [comment]
修复开启多流情况下，无远端视频。 修复测试无法登录问题。

**Comment by zjlizhipeng** [comment]
添加在会中展示‘会议信息音视频参数’。
